# Generated by Django 3.2.6 on 2021-10-23 07:40

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='quote',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
