# Generated by Django 5.2.17 on 2026-09-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_seed_new_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="author",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=150),
        ),
    ]
